version: 0.2

env:
  secrets-manager:
    TF_VAR_ROLE_ARN: my-role:arn
    TF_VAR_ECR_CODEBUILDROLE_ARN: ecr-codebuildrole: arn
phases:
  install:
    commands:
      - "cd /usr/bin"
      - "curl -s -qL -o terraform.zip https://releases.hashicorp.com/terraform/0.12.26/terraform_0.12.26_linux_amd64.zip"
      - "unzip -o terraform.zip"

  build:
    commands:
      - cd "$CODEBUILD_SRC_DIR"
      - terraform init
      - terraform validate
      - terraform plan
      - terraform apply -auto-approve

  post_build:
    commands:
      - echo "Terraform completed on `date`"
